project:
  type: website
  output-dir: docs

website:
  favicon: assets/icon.ico
  image: assets/icon.ico
  page-footer:
    center: "github pages using quarto • copyright © 2026 dmitry petrov • all rights reserved."
  
  sidebar:
    id: main-nav
    title: "neurallystronger"
    style: "docked"
    search: false
    contents:
      - text: "art"
        file: art/index.qmd
        
      - text: "&thinsp;"
    
      - text: "longer writing"
        file: essays/index.qmd
      - text: "shorter writing"
        file: articles/index.qmd
        
      - text: "&thinsp;"
        
      - text: "academic work"
        file: academic/index.qmd
      - text: "reviews"
        file: reviews/index.qmd
        
      - text: "&thinsp;"
        
      - text: "my two disabilities"
        file: disabilities/index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    mainfont: '"Times New Roman", Times, Georgia, serif'