---
title: "Academic Work"
title-block-style: none
pagetitle: "Academic Work"
---


### Working Papers

***On P-Zombies, Synaptogenesis, and Dopaminergic Degeneration*** \[PDF later\] *(2026)*  
*Philosophy. Tags: Chalmers, 1996 ; Multiple Realizability ; Action ; Parkinson's Disease*  
[**Background**]{.underline}: Reading Chalmers is *sometimes* eyebrow-raising and *always* thought-provoking.  
[**Motivating**]{.underline}: There's not much philosophical zombie discussion relating to trauma and this continuation was immediately interesting to me; as an innocent hobbyist I do not hold a side in the consciousness debate (yet) -- I am seeing where my wandering mind takes me.  

::: {.callout-note collapse="false"}

### Abstract

A philosophical zombie (p-zombie) "lacking *conscious* experience" is canonically presumed to be "atom for atom" similar to its human counterpart, yet little neurophilosophical elaboration exists about the p-zombie's temporal brain potential, i.e., its neuroplasticity ability. I propose a fruitful extension to the p-zombie puzzle: 1) "Changes in the Brain" reframes the discussion in terms of a hypothetical mildest Traumatic Brain Injury (mstTBI) that is similar to a p-zombie; 2) "What is Consciousness?" posits mild TBI (mTBI) can allow a "full" recovery, meaning we are able to isolate whether consciousness (valence) is process (synapses, representationalism) or goal (neurons, intrinsic quale) oriented; 3) "Consciousness under Duress" exploits my qualia of having a Grade 3 Diffuse Axonal Injury to discuss, with limited confidence, if severe TBI recoveries allow us to glimpse into *Consciousness* and human *Action*.

:::

___

***Statistics of Counterfactual Decision-Making: Lessons from Graduate Economics Enrollment*** \[[PDF](counterfactuals.pdf)\] [(data on request)]{.small-text} *(2022--Present)*  
*Economics. Tags: Sapienza, 2009 ; Decision-making ; (continue working, I like Berkson's continuation)*  
[**Background**]{.underline}: While merrily deriving matrix calculus beta-hats and working through Gauss-Markov as a sophomore, I realized I do not actually know anything about Economics PhD admissions as an immigrant \& a CC transfer.  
[**Motivating**]{.underline}: The only reasonable thing was to use departmental websites, LinkedIn, and the internet to compile a list of 547 enrollees into 2021-2022 "better" PhD programs and see what is up. Of course, not all admits choose to enroll, and I only had enrollment data.  

::: {.callout-note collapse="false"}

### Abstract

When an undergraduate is faced with a decision to enroll into a T7 economics department, **female** seniors choose to enroll at 2.7x times **male** seniors do (2021-2022 admission cohorts, $N=314$, $p=0.02247$, *CI=entirely positive*). Why? I discuss econometric and behavioral explanations.

[I wrote up this LaTeX PDF in 2026 around 2 years after my trauma; I do continue working on it.]{.small-text}
:::