---
title: "Induction, Metaphysical Fears, and the Gradient of Reality"
title-block-style: none
sidebar: main-nav
---

[Reality is a fragile jenga tower of inductions.]{.small-text}

**Read:**  
*Fact, Fiction, and Forecast*  
*Attention is All You Need*

- [1. Motivating](#motivating)
- [2. Contemplating "escaping" myself](#lesson)
- [3. Concluding](#concluding)

### Motivating {#motivating}

My day-to-day memory returned three days before my transfer to the Harborview rehabilitation floor 20 days after my hospitalization. By the time I was entering Rehab, my memory was functioning well: I can describe the move from Internal Medicine to Rehab - it was an exercise. We (a physical therapist and I) took the elevator, and I was given a significant task: finding my new room by myself. Awkwardly waddling like a penguin plopping tiny steps, intently staring at the signs above the doors, and having no spatial awareness of the tacitly accommodating rehab staff nearby -- just desperately holding onto the room number in my head before it dissipates -- I found the room! I was quite proud of myself.

The night before my day-to-day memory returned, I was restless in **acute delirium**, partially removing my hand's splint. I think an orthopedics male nurse fixing my splint later that day is the very first thing I remember. **Why did my memory return there?** My deepest, most abstract consciousness accepted that *this* is a single world. Note that it didn't verify whether *this* is real or fake. The consciousness just recognized that whatever *this* is, it is continuous. How? I can only theorize some opportunity that fated day allowed me to experience the passing of the day, and my consciousness dove into an old philosophy idea -- the riddle of induction. Poor discrete little me. **I saw days pass, and I broke down in raged delirium**. I "proved" to myself, *by induction*, the days are linked and I should be utilizing my day-to-day memory. My surface-level consciousness then tried to find a familiar first-person heuristic: *this* quickly became a dream or a video game. All these therapists, all these doctors, all these nurses. All these new people I have never met before. They knew my name, they knew so much about me. They appeared in my field of vision when I needed something. *Yet they were nameless*.

I spent May 31 to June 6, 2024 in Rehabilitation. The feeling of rapidly regaining function under medical supervision can be described (relevantly but also truly appropriately) as a first-person video game where you need to progress through quests and levels – an endless game-like procedure. You learn to turn your head, you learn to keep upright, you learn to orient yourself to common anchors of *this* world, such as current date and location. Tasks and subsequent autonomy were achieved quicker than the full consciousness and agency returned. Some things were mechanistic and automatic – I’d enter the passcode of my iPad with no hesitation, I’d gulp down the Protein Shakes my younger brother for some reason bought me with no hesitation, I’d handle my hearing aid (other broke during my fall) with no hesitation. One may think: these are just some of the procedures you have Long-Term Potentiation in… But,

I visited the rehabilitation exercise room during Physical Therapy and saw a wall with unrelated light dumbbells – experiencing a desire to grab a dumbbell. I was hesitating, I was afraid to deviate from the PT, and I deliberated the action carefully. This alien equipment is not part of my existing procedure. I froze for ten seconds, and you could almost hear my brain clicking– before grabbing a dumbbell with my non-shattered hand. My mind reset after. OK, you grabbed it as you desired, but what is next in your chain of action? **What do you induce now?** Retrospectively, I wanted to attempt some Lateral Raises, my favorite and most frequent exercise, but the fact you extend the arm away from the body terrified me (proprioception and balance). I weakly imitated the movement and quit. In the end, I just awkwardly did some Bicep Curls (thinking why weight training feels so familiar). Curls: seeing the dumbbell without needing to turn the head, as well as acting without needing to be aware of the space to your side – that’s less restraints the brain considers vs. Lateral Raises. My CNS needs less prompting to wake up. And I never do this exercise, not even for laughs or show-offs! Yet I did then! *This is important*: I chose to perform an action I never do instead of the one I have most practice with because I saw the restraints being less.

**REFRAME:** we do not fear the unknown, we fear deviation into more restraints. Little children do not fear the dark because "...it is dark”, “...it is unknown”, “...some ancient wisdom is genetically ingrained”. Precisely, little children fear the dark because of the enormous set of possible restraints they forecast into the darkness. Adults heuristically limit this set.

Big sets confuse and terrify us.[^1]

[^1]: Current Language Machine Intelligence crudely mimics a young child — the softmax dot product thus was scaled by frac\{1\}\{sqrt\{d_k\}\} precisely to counteract this abstract “fear of the darkness” and make the output remotely interpretable for adult humans.

### Contemplating "escaping" myself {#lesson}

### Concluding {#concluding}
