---
title: "Happy 250th Birthday, America."
title-block-style: none
sidebar: main-nav
---

[This is a shorter comment.]{.small-text}

**Acknowledged:**  
*The Pledge of Allegiance*  
*Google Translate*

### American English

American English uniquely separates *Freedom* and *Liberty*.

As I am from Siberia, with confidence:

- **Russian:** "свобода" (svoboda) both.

Sketching with Google Translate:

- **Germanic Languages:** versions of "freiheit" both.
- **Latin Languages:** versions of "libertas" both.
- **Greek:** "ελευθερία" (eleftheria) both.
- **Arabic:** "حرية" huriya / "الحرية" alhuriya.
- **Hindi:** "स्वतंत्रता" (swatantrata) both.
- **Chinese:** "自由" (ziyou) both.
- **Japanese:** "自由" (jiyu) both.
- **Korean:** "자유" (jayu) both.

Google Translate picks up the difference for Arabic a little, somewhat differentiating freedom (huriya) and liberty (alhuriya). I have also looked at Bengali, Urdu, Swahili, Amharic, Yoruba.

American English looked at both Germanic "freiheit" and Latin "libertas", and decided that both are important. So important that it used both.

I noticed this two months before I randomly fell 40 ft offtrail and almost died in the mountains before being found.

### Interpretation

- How did I interpret this *abstractly*?

Graph: X is time and Y is "ability to". "Freedom" implies there is no upper bound, no *restraint* on the amount of ***ability to*** one may have. "Liberty" implies an existence of a positive lower bound on the amount of ***ability to***. No matter how *restrained* you are in society, your ***ability to*** is always greater than your ***dis-ability to***.

**The word "Freedom" has no implication that the "ability to" needs stay positive.**

I *love* America. I look at its foundations with pure adoration and jubilation.

- How did I interpret this *socioeconomically*?

I can't even begin describing it post my brain injury. My voice breaks down into evil guttural sounds. My face starts twitching. My eyes see no darkness. My eyes see a blinding white of pure rage.

America's statue is of *liberty*. In schools, we ended the pledge of allegiance: "...with *liberty* and justice for all". Yet since the Cold War, America, in its haste to differentiate from the Soviet Union, became about "freedom". We use liberty less in our lexicon, we mistake liberty's intention, we dilute liberty's meaning.

[Because of course the world is *boolean*. True and False. 0 and 1. Black and white. Us and them. Left and Right. USA and USSR. ***Freiheit and Libertas.*** Wouldn't a staunch atheist be as deplorable as a fanatical believer, in their hypocrisy engaging in the same thinking, just from a different viewpoint? There is for sure no higher power! There for sure is! Humans are fleeting and thus need an urgent meaning. In desperation, humans converge their *confidence* to 100%.]{.small-text}

Well, since the generations that were born in the 1950s do not care about whether their ***ability to*** is positively bounded -- just that it can go up infinitely, like their precious stock market -- why not take their ***ability to*** beat their colorless hearts? Now they whimper about their liberty, not so caring about yours.

True societal freedom is a consequence of liberty. Without liberty, society's freedom is a mere *martingale*, ready to collapse into authoritarianism's ***dis-ability to***.

Happy 250th birthday, America.

::: {style="text-align: right;"}
— dvp, July 4th, 2026  
[Don't be stupid.]{.small-text}
:::