---
title: "How to sleep"
title-block-style: none
sidebar: main-nav
---

___

WORK-IN-PROGRESS

___

::: {.callout-tip collapse="false"}
## I motivate this article:

*When I was discharged June 6, I had to be in a wheelchair. I couldn't balance. I struggled undressing and stepping over the bathtub to shower. I could not walk the (actual) curb. I fell standing on one leg. This is expected with a devastated cerebral peduncle. A month later, I went to **sleep**; immediately upon waking up, without even getting out of bed -- the moment my eyes opened -- I was sure I could walk the curb. I just knew. I urged family to provide backup and we went to test. Yes, I could. My outpatient Physical Therapy only had four 1 hour visits lasting mid-July to mid-August.*
:::

I seem to naturally sleep productively.  
But not everyone *sleeps productively* (quality), and not everyone *gets a lot of sleep* (quantity). I repeat -- I separate the two.  
Let's help those people. Let's talk sleep.

___

### Intuitions

**Sleep is the ~33\% most similar of ALL lives.** Have you thought about it like that?  
[What's your excuse to not have briefly contemplated the abundant academic Sleep literature in Psychiatry?]{.small-text}

I suppose I did that for you. From <a href="https://scholar.google.com/citations?user=x6uUysgAAAAJ" target="_blank"><em>Tononi</em></a>, to parsing the <a href="https://www.sleep.pitt.edu/psqi" target="_blank"><em>PSQI</em></a> article, to reading all those endless college student cognitive-sleep studies. All to seek insights into **neurorehabilitation** in hopes others mimic my DAI 3 recovery success, and mine persists for decades.

Perhaps you shrug off the importance of sleep: "Why? I'm not conscious during it anyway".  
Sleep is when we recover and internalize.  

**Reframe a perfect day:**  
*me today* = *recovery/internalization*(*me yesterday*) + *error*  
*me* = *sleep*() + *error*  
[This is very simplified.]{.small-text}

___

### Quantity, Quality

___

### The Glymphatic System

[[Jessen NA, Munk AS, Lundgaard I, Nedergaard M. The Glymphatic System: A Beginner's Guide](https://pmc.ncbi.nlm.nih.gov/articles/PMC4636982/)]{.small-text}


